### ISSUE TITLE
Android App Missing

### ISSUE THREAD

**Issue by dustingooding** [deathgrindfreak/clashcallermobile#1]
The app was available but is no longer listed. I was able to install it on my phone.  Now that I want it on my tablet, it's gone.  :/

**Comment by deathgrindfreak** [comment]
Yeah sorry about that, google suspended it and is not allowing me to put it back up for some reason.  I'll let you know when I finally get it back up.

<div>-------- Original message --------</div><div>From: dustingooding notifications@github.com </div><div>Date:06/16/2015  9:39 PM  (GMT-06:00) </div><div>To: deathgrindfreak/clashcallermobile clashcallermobile@noreply.github.com </div><div>Cc:  </div><div>Subject: [clashcallermobile] Android App Missing (#1) </div><div>
</div>The app was available but is no longer listed. I was able to install it on my phone. Now that I want it on my tablet, it's gone. :/

**Comment by deathgrindfreak** [comment]
Finally got google to approve the new version, so it's back up in the store now: 

https://play.google.com/store/apps/details?id=io.deathgrindfreak.clashcaller

<div>-------- Original message --------</div><div>From: dustingooding notifications@github.com </div><div>Date:06/16/2015  9:39 PM  (GMT-06:00) </div><div>To: deathgrindfreak/clashcallermobile clashcallermobile@noreply.github.com </div><div>Cc:  </div><div>Subject: [clashcallermobile] Android App Missing (#1) </div><div>
</div>The app was available but is no longer listed. I was able to install it on my phone. Now that I want it on my tablet, it's gone. :/
